version: '3.8'
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-dev
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dev-data:/home/node/.n8n
      - ./dist:/home/node/.n8n/custom/node_modules/n8n-nodes-nimbasms
    environment:
      - NODE_ENV=development
      - N8N_LOG_LEVEL=debug 